/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RecompensasRouteImport } from './routes/recompensas'
import { Route as LojaRouteImport } from './routes/loja'
import { Route as LoginRouteImport } from './routes/login'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RecompensasIndexRouteImport } from './routes/recompensas.index'
import { Route as RecompensasMinhaContaRouteImport } from './routes/recompensas.minha-conta'
import { Route as RecompensasLoginRouteImport } from './routes/recompensas.login'
import { Route as ReciboTokenRouteImport } from './routes/recibo.$token'
import { Route as FaturaTokenRouteImport } from './routes/fatura.$token'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin.index'
import { Route as AuthenticatedAdminUtmRouteImport } from './routes/_authenticated/admin.utm'
import { Route as AuthenticatedAdminRecompensasRouteImport } from './routes/_authenticated/admin.recompensas'
import { Route as AuthenticatedAdminRecibosRouteImport } from './routes/_authenticated/admin.recibos'
import { Route as AuthenticatedAdminProdutosRouteImport } from './routes/_authenticated/admin.produtos'
import { Route as AuthenticatedAdminPedidosRouteImport } from './routes/_authenticated/admin.pedidos'
import { Route as AuthenticatedAdminOrcamentosRouteImport } from './routes/_authenticated/admin.orcamentos'
import { Route as AuthenticatedAdminNfeRouteImport } from './routes/_authenticated/admin.nfe'
import { Route as AuthenticatedAdminKanbanRouteImport } from './routes/_authenticated/admin.kanban'
import { Route as AuthenticatedAdminFaturasRouteImport } from './routes/_authenticated/admin.faturas'
import { Route as AuthenticatedAdminEquipeRouteImport } from './routes/_authenticated/admin.equipe'
import { Route as AuthenticatedAdminDevRouteImport } from './routes/_authenticated/admin.dev'
import { Route as AuthenticatedAdminClientesRouteImport } from './routes/_authenticated/admin.clientes'
import { Route as AuthenticatedAdminBrandingRouteImport } from './routes/_authenticated/admin.branding'
import { Route as AuthenticatedAdminAnalisesRouteImport } from './routes/_authenticated/admin.analises'

const RecompensasRoute = RecompensasRouteImport.update({
  id: '/recompensas',
  path: '/recompensas',
  getParentRoute: () => rootRouteImport,
} as any)
const LojaRoute = LojaRouteImport.update({
  id: '/loja',
  path: '/loja',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RecompensasIndexRoute = RecompensasIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => RecompensasRoute,
} as any)
const RecompensasMinhaContaRoute = RecompensasMinhaContaRouteImport.update({
  id: '/minha-conta',
  path: '/minha-conta',
  getParentRoute: () => RecompensasRoute,
} as any)
const RecompensasLoginRoute = RecompensasLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => RecompensasRoute,
} as any)
const ReciboTokenRoute = ReciboTokenRouteImport.update({
  id: '/recibo/$token',
  path: '/recibo/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const FaturaTokenRoute = FaturaTokenRouteImport.update({
  id: '/fatura/$token',
  path: '/fatura/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdminUtmRoute = AuthenticatedAdminUtmRouteImport.update({
  id: '/admin/utm',
  path: '/admin/utm',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdminRecompensasRoute =
  AuthenticatedAdminRecompensasRouteImport.update({
    id: '/admin/recompensas',
    path: '/admin/recompensas',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminRecibosRoute =
  AuthenticatedAdminRecibosRouteImport.update({
    id: '/admin/recibos',
    path: '/admin/recibos',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminProdutosRoute =
  AuthenticatedAdminProdutosRouteImport.update({
    id: '/admin/produtos',
    path: '/admin/produtos',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminPedidosRoute =
  AuthenticatedAdminPedidosRouteImport.update({
    id: '/admin/pedidos',
    path: '/admin/pedidos',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminOrcamentosRoute =
  AuthenticatedAdminOrcamentosRouteImport.update({
    id: '/admin/orcamentos',
    path: '/admin/orcamentos',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminNfeRoute = AuthenticatedAdminNfeRouteImport.update({
  id: '/admin/nfe',
  path: '/admin/nfe',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdminKanbanRoute =
  AuthenticatedAdminKanbanRouteImport.update({
    id: '/admin/kanban',
    path: '/admin/kanban',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminFaturasRoute =
  AuthenticatedAdminFaturasRouteImport.update({
    id: '/admin/faturas',
    path: '/admin/faturas',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminEquipeRoute =
  AuthenticatedAdminEquipeRouteImport.update({
    id: '/admin/equipe',
    path: '/admin/equipe',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminDevRoute = AuthenticatedAdminDevRouteImport.update({
  id: '/admin/dev',
  path: '/admin/dev',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdminClientesRoute =
  AuthenticatedAdminClientesRouteImport.update({
    id: '/admin/clientes',
    path: '/admin/clientes',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminBrandingRoute =
  AuthenticatedAdminBrandingRouteImport.update({
    id: '/admin/branding',
    path: '/admin/branding',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminAnalisesRoute =
  AuthenticatedAdminAnalisesRouteImport.update({
    id: '/admin/analises',
    path: '/admin/analises',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/checkout': typeof CheckoutRoute
  '/login': typeof LoginRoute
  '/loja': typeof LojaRoute
  '/recompensas': typeof RecompensasRouteWithChildren
  '/fatura/$token': typeof FaturaTokenRoute
  '/recibo/$token': typeof ReciboTokenRoute
  '/recompensas/login': typeof RecompensasLoginRoute
  '/recompensas/minha-conta': typeof RecompensasMinhaContaRoute
  '/recompensas/': typeof RecompensasIndexRoute
  '/admin/analises': typeof AuthenticatedAdminAnalisesRoute
  '/admin/branding': typeof AuthenticatedAdminBrandingRoute
  '/admin/clientes': typeof AuthenticatedAdminClientesRoute
  '/admin/dev': typeof AuthenticatedAdminDevRoute
  '/admin/equipe': typeof AuthenticatedAdminEquipeRoute
  '/admin/faturas': typeof AuthenticatedAdminFaturasRoute
  '/admin/kanban': typeof AuthenticatedAdminKanbanRoute
  '/admin/nfe': typeof AuthenticatedAdminNfeRoute
  '/admin/orcamentos': typeof AuthenticatedAdminOrcamentosRoute
  '/admin/pedidos': typeof AuthenticatedAdminPedidosRoute
  '/admin/produtos': typeof AuthenticatedAdminProdutosRoute
  '/admin/recibos': typeof AuthenticatedAdminRecibosRoute
  '/admin/recompensas': typeof AuthenticatedAdminRecompensasRoute
  '/admin/utm': typeof AuthenticatedAdminUtmRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/checkout': typeof CheckoutRoute
  '/login': typeof LoginRoute
  '/loja': typeof LojaRoute
  '/fatura/$token': typeof FaturaTokenRoute
  '/recibo/$token': typeof ReciboTokenRoute
  '/recompensas/login': typeof RecompensasLoginRoute
  '/recompensas/minha-conta': typeof RecompensasMinhaContaRoute
  '/recompensas': typeof RecompensasIndexRoute
  '/admin/analises': typeof AuthenticatedAdminAnalisesRoute
  '/admin/branding': typeof AuthenticatedAdminBrandingRoute
  '/admin/clientes': typeof AuthenticatedAdminClientesRoute
  '/admin/dev': typeof AuthenticatedAdminDevRoute
  '/admin/equipe': typeof AuthenticatedAdminEquipeRoute
  '/admin/faturas': typeof AuthenticatedAdminFaturasRoute
  '/admin/kanban': typeof AuthenticatedAdminKanbanRoute
  '/admin/nfe': typeof AuthenticatedAdminNfeRoute
  '/admin/orcamentos': typeof AuthenticatedAdminOrcamentosRoute
  '/admin/pedidos': typeof AuthenticatedAdminPedidosRoute
  '/admin/produtos': typeof AuthenticatedAdminProdutosRoute
  '/admin/recibos': typeof AuthenticatedAdminRecibosRoute
  '/admin/recompensas': typeof AuthenticatedAdminRecompensasRoute
  '/admin/utm': typeof AuthenticatedAdminUtmRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/checkout': typeof CheckoutRoute
  '/login': typeof LoginRoute
  '/loja': typeof LojaRoute
  '/recompensas': typeof RecompensasRouteWithChildren
  '/fatura/$token': typeof FaturaTokenRoute
  '/recibo/$token': typeof ReciboTokenRoute
  '/recompensas/login': typeof RecompensasLoginRoute
  '/recompensas/minha-conta': typeof RecompensasMinhaContaRoute
  '/recompensas/': typeof RecompensasIndexRoute
  '/_authenticated/admin/analises': typeof AuthenticatedAdminAnalisesRoute
  '/_authenticated/admin/branding': typeof AuthenticatedAdminBrandingRoute
  '/_authenticated/admin/clientes': typeof AuthenticatedAdminClientesRoute
  '/_authenticated/admin/dev': typeof AuthenticatedAdminDevRoute
  '/_authenticated/admin/equipe': typeof AuthenticatedAdminEquipeRoute
  '/_authenticated/admin/faturas': typeof AuthenticatedAdminFaturasRoute
  '/_authenticated/admin/kanban': typeof AuthenticatedAdminKanbanRoute
  '/_authenticated/admin/nfe': typeof AuthenticatedAdminNfeRoute
  '/_authenticated/admin/orcamentos': typeof AuthenticatedAdminOrcamentosRoute
  '/_authenticated/admin/pedidos': typeof AuthenticatedAdminPedidosRoute
  '/_authenticated/admin/produtos': typeof AuthenticatedAdminProdutosRoute
  '/_authenticated/admin/recibos': typeof AuthenticatedAdminRecibosRoute
  '/_authenticated/admin/recompensas': typeof AuthenticatedAdminRecompensasRoute
  '/_authenticated/admin/utm': typeof AuthenticatedAdminUtmRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/checkout'
    | '/login'
    | '/loja'
    | '/recompensas'
    | '/fatura/$token'
    | '/recibo/$token'
    | '/recompensas/login'
    | '/recompensas/minha-conta'
    | '/recompensas/'
    | '/admin/analises'
    | '/admin/branding'
    | '/admin/clientes'
    | '/admin/dev'
    | '/admin/equipe'
    | '/admin/faturas'
    | '/admin/kanban'
    | '/admin/nfe'
    | '/admin/orcamentos'
    | '/admin/pedidos'
    | '/admin/produtos'
    | '/admin/recibos'
    | '/admin/recompensas'
    | '/admin/utm'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/checkout'
    | '/login'
    | '/loja'
    | '/fatura/$token'
    | '/recibo/$token'
    | '/recompensas/login'
    | '/recompensas/minha-conta'
    | '/recompensas'
    | '/admin/analises'
    | '/admin/branding'
    | '/admin/clientes'
    | '/admin/dev'
    | '/admin/equipe'
    | '/admin/faturas'
    | '/admin/kanban'
    | '/admin/nfe'
    | '/admin/orcamentos'
    | '/admin/pedidos'
    | '/admin/produtos'
    | '/admin/recibos'
    | '/admin/recompensas'
    | '/admin/utm'
    | '/admin'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/checkout'
    | '/login'
    | '/loja'
    | '/recompensas'
    | '/fatura/$token'
    | '/recibo/$token'
    | '/recompensas/login'
    | '/recompensas/minha-conta'
    | '/recompensas/'
    | '/_authenticated/admin/analises'
    | '/_authenticated/admin/branding'
    | '/_authenticated/admin/clientes'
    | '/_authenticated/admin/dev'
    | '/_authenticated/admin/equipe'
    | '/_authenticated/admin/faturas'
    | '/_authenticated/admin/kanban'
    | '/_authenticated/admin/nfe'
    | '/_authenticated/admin/orcamentos'
    | '/_authenticated/admin/pedidos'
    | '/_authenticated/admin/produtos'
    | '/_authenticated/admin/recibos'
    | '/_authenticated/admin/recompensas'
    | '/_authenticated/admin/utm'
    | '/_authenticated/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  CheckoutRoute: typeof CheckoutRoute
  LoginRoute: typeof LoginRoute
  LojaRoute: typeof LojaRoute
  RecompensasRoute: typeof RecompensasRouteWithChildren
  FaturaTokenRoute: typeof FaturaTokenRoute
  ReciboTokenRoute: typeof ReciboTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/recompensas': {
      id: '/recompensas'
      path: '/recompensas'
      fullPath: '/recompensas'
      preLoaderRoute: typeof RecompensasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/loja': {
      id: '/loja'
      path: '/loja'
      fullPath: '/loja'
      preLoaderRoute: typeof LojaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recompensas/': {
      id: '/recompensas/'
      path: '/'
      fullPath: '/recompensas/'
      preLoaderRoute: typeof RecompensasIndexRouteImport
      parentRoute: typeof RecompensasRoute
    }
    '/recompensas/minha-conta': {
      id: '/recompensas/minha-conta'
      path: '/minha-conta'
      fullPath: '/recompensas/minha-conta'
      preLoaderRoute: typeof RecompensasMinhaContaRouteImport
      parentRoute: typeof RecompensasRoute
    }
    '/recompensas/login': {
      id: '/recompensas/login'
      path: '/login'
      fullPath: '/recompensas/login'
      preLoaderRoute: typeof RecompensasLoginRouteImport
      parentRoute: typeof RecompensasRoute
    }
    '/recibo/$token': {
      id: '/recibo/$token'
      path: '/recibo/$token'
      fullPath: '/recibo/$token'
      preLoaderRoute: typeof ReciboTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fatura/$token': {
      id: '/fatura/$token'
      path: '/fatura/$token'
      fullPath: '/fatura/$token'
      preLoaderRoute: typeof FaturaTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/utm': {
      id: '/_authenticated/admin/utm'
      path: '/admin/utm'
      fullPath: '/admin/utm'
      preLoaderRoute: typeof AuthenticatedAdminUtmRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/recompensas': {
      id: '/_authenticated/admin/recompensas'
      path: '/admin/recompensas'
      fullPath: '/admin/recompensas'
      preLoaderRoute: typeof AuthenticatedAdminRecompensasRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/recibos': {
      id: '/_authenticated/admin/recibos'
      path: '/admin/recibos'
      fullPath: '/admin/recibos'
      preLoaderRoute: typeof AuthenticatedAdminRecibosRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/produtos': {
      id: '/_authenticated/admin/produtos'
      path: '/admin/produtos'
      fullPath: '/admin/produtos'
      preLoaderRoute: typeof AuthenticatedAdminProdutosRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/pedidos': {
      id: '/_authenticated/admin/pedidos'
      path: '/admin/pedidos'
      fullPath: '/admin/pedidos'
      preLoaderRoute: typeof AuthenticatedAdminPedidosRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/orcamentos': {
      id: '/_authenticated/admin/orcamentos'
      path: '/admin/orcamentos'
      fullPath: '/admin/orcamentos'
      preLoaderRoute: typeof AuthenticatedAdminOrcamentosRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/nfe': {
      id: '/_authenticated/admin/nfe'
      path: '/admin/nfe'
      fullPath: '/admin/nfe'
      preLoaderRoute: typeof AuthenticatedAdminNfeRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/kanban': {
      id: '/_authenticated/admin/kanban'
      path: '/admin/kanban'
      fullPath: '/admin/kanban'
      preLoaderRoute: typeof AuthenticatedAdminKanbanRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/faturas': {
      id: '/_authenticated/admin/faturas'
      path: '/admin/faturas'
      fullPath: '/admin/faturas'
      preLoaderRoute: typeof AuthenticatedAdminFaturasRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/equipe': {
      id: '/_authenticated/admin/equipe'
      path: '/admin/equipe'
      fullPath: '/admin/equipe'
      preLoaderRoute: typeof AuthenticatedAdminEquipeRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/dev': {
      id: '/_authenticated/admin/dev'
      path: '/admin/dev'
      fullPath: '/admin/dev'
      preLoaderRoute: typeof AuthenticatedAdminDevRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/clientes': {
      id: '/_authenticated/admin/clientes'
      path: '/admin/clientes'
      fullPath: '/admin/clientes'
      preLoaderRoute: typeof AuthenticatedAdminClientesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/branding': {
      id: '/_authenticated/admin/branding'
      path: '/admin/branding'
      fullPath: '/admin/branding'
      preLoaderRoute: typeof AuthenticatedAdminBrandingRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/analises': {
      id: '/_authenticated/admin/analises'
      path: '/admin/analises'
      fullPath: '/admin/analises'
      preLoaderRoute: typeof AuthenticatedAdminAnalisesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedAdminAnalisesRoute: typeof AuthenticatedAdminAnalisesRoute
  AuthenticatedAdminBrandingRoute: typeof AuthenticatedAdminBrandingRoute
  AuthenticatedAdminClientesRoute: typeof AuthenticatedAdminClientesRoute
  AuthenticatedAdminDevRoute: typeof AuthenticatedAdminDevRoute
  AuthenticatedAdminEquipeRoute: typeof AuthenticatedAdminEquipeRoute
  AuthenticatedAdminFaturasRoute: typeof AuthenticatedAdminFaturasRoute
  AuthenticatedAdminKanbanRoute: typeof AuthenticatedAdminKanbanRoute
  AuthenticatedAdminNfeRoute: typeof AuthenticatedAdminNfeRoute
  AuthenticatedAdminOrcamentosRoute: typeof AuthenticatedAdminOrcamentosRoute
  AuthenticatedAdminPedidosRoute: typeof AuthenticatedAdminPedidosRoute
  AuthenticatedAdminProdutosRoute: typeof AuthenticatedAdminProdutosRoute
  AuthenticatedAdminRecibosRoute: typeof AuthenticatedAdminRecibosRoute
  AuthenticatedAdminRecompensasRoute: typeof AuthenticatedAdminRecompensasRoute
  AuthenticatedAdminUtmRoute: typeof AuthenticatedAdminUtmRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAdminAnalisesRoute: AuthenticatedAdminAnalisesRoute,
  AuthenticatedAdminBrandingRoute: AuthenticatedAdminBrandingRoute,
  AuthenticatedAdminClientesRoute: AuthenticatedAdminClientesRoute,
  AuthenticatedAdminDevRoute: AuthenticatedAdminDevRoute,
  AuthenticatedAdminEquipeRoute: AuthenticatedAdminEquipeRoute,
  AuthenticatedAdminFaturasRoute: AuthenticatedAdminFaturasRoute,
  AuthenticatedAdminKanbanRoute: AuthenticatedAdminKanbanRoute,
  AuthenticatedAdminNfeRoute: AuthenticatedAdminNfeRoute,
  AuthenticatedAdminOrcamentosRoute: AuthenticatedAdminOrcamentosRoute,
  AuthenticatedAdminPedidosRoute: AuthenticatedAdminPedidosRoute,
  AuthenticatedAdminProdutosRoute: AuthenticatedAdminProdutosRoute,
  AuthenticatedAdminRecibosRoute: AuthenticatedAdminRecibosRoute,
  AuthenticatedAdminRecompensasRoute: AuthenticatedAdminRecompensasRoute,
  AuthenticatedAdminUtmRoute: AuthenticatedAdminUtmRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

interface RecompensasRouteChildren {
  RecompensasLoginRoute: typeof RecompensasLoginRoute
  RecompensasMinhaContaRoute: typeof RecompensasMinhaContaRoute
  RecompensasIndexRoute: typeof RecompensasIndexRoute
}

const RecompensasRouteChildren: RecompensasRouteChildren = {
  RecompensasLoginRoute: RecompensasLoginRoute,
  RecompensasMinhaContaRoute: RecompensasMinhaContaRoute,
  RecompensasIndexRoute: RecompensasIndexRoute,
}

const RecompensasRouteWithChildren = RecompensasRoute._addFileChildren(
  RecompensasRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  CheckoutRoute: CheckoutRoute,
  LoginRoute: LoginRoute,
  LojaRoute: LojaRoute,
  RecompensasRoute: RecompensasRouteWithChildren,
  FaturaTokenRoute: FaturaTokenRoute,
  ReciboTokenRoute: ReciboTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
